CREATE DATABASE ORG;
SHOW DATABASES;
USE ORG;

CREATE TABLE worker(
WORKER_ID  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
SALARY INT (15),
JOINING_DATE DATETIME,
DEPARTMENT VARCHAR(255)
);

INSERT INTO worker VALUES(1,'OM','KALDATE',10000,'11-12-13 11.12.01','HR');
INSERT INTO worker(WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
(2,'RAM','KALDATE',100,'11-12-13 10.12.10','CEO'),
(3,'GANDHI','MAHAN',150,'11-02-13 11.12.10','CEO');
INSERT INTO worker VALUES
(4,'NAVNATH','NARWADE',2000,'28-4-22 09.18.25','EMPLOYEE'),
(5,'ABHINAV','KALDATE',2500,'29-8-27 10.11.12','MANAGER');

SELECT*FROM worker;
DROP TABLE worker;
SELECT WORKER_ID , DEPARTMENT FROM worker;
SELECT 11+4;
SELECT now();
SELECT lcase('OM KALDATE');
SELECT * FROM worker WHERE salary <200;

SELECT*FROM worker WHERE DEPARTMENT = 'HR';
SELECT*FROM worker WHERE salary BETWEEN 100 AND 200;
SELECT*FROM worker WHERE SALARY = 100 OR SALARY = 150;
SELECT*FROM worker WHERE DEPARTMENT IN ('HR','CEO');
SELECT * FROM worker WHERE SALARY IS NULL;
SELECT*FROM worker WHERE FIRST_NAME LIKE '_M' ; 
SELECT * FROM worker ORDER BY  salary;
SELECT * FROM worker ORDER BY  salary DESC;
SELECT DISTINCT DEPARTMENT FROM worker;
SELECT DEPARTMENT,COUNT(DEPARTMENT) FROM worker GROUP BY DEPARTMENT;
SELECT DEPARTMENT ,AVG(SALARY) FROM worker GROUP BY DEPARTMENT;
SELECT DEPARTMENT,MIN(SALARY) FROM wroker GROUP BY DEPARTMENT; 
SELECT DEPARTMENT,sum(SALARY) FROM wroker GROUP BY DEPARTMENT; 
SELECT DEPARTMENT ,COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT) >1;







